name = "DuckDBDebug"
uuid = "e5d671a7-4186-4f1a-bf88-c19b630da94f"
authors = ["Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
