name: Test

on:
  push:
    branches:
      - main
    tags: ["*"]

  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      allow_failure: ${{ matrix.allow_failure }}
      run_codecov: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
      duckdb_jll_version: ${{ matrix.duckdb_jll_version }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1"
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        duckdb_jll_version:
          - "v1.0.0"
          - "v1.1.0"
        allow_failure: [false]
